name: iOS Simulator Test

on:
  workflow_dispatch: # 手動実行のトリガー

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - name: Install Playwright
      run: |
        npm install @playwright/test
        npx playwright install --with-deps

    - name: Create and run Playwright test
      run: |
        echo "const path = require('path');" > test.js
        echo "const { chromium } = require('playwright');" >> test.js
        echo "(async () => {" >> test.js
        echo "    await require('child_process').execSync('xcrun simctl boot \"iPhone 15\"');" >> test.js
        echo "    const browser = await chromium.launch({ headless: false });" >> test.js
        echo "    const context = await browser.newContext();" >> test.js
        echo "    const page = await context.newPage();" >> test.js
        echo "    await page.goto('https://www.google.com');" >> test.js
        echo "    await page.screenshot({ path: path.join('screen_shot', 'google_screenshot.png') });" >> test.js
        echo "    await page.fill('textarea[name=\"q\"]', 'アニメ');" >> test.js
        echo "    await page.keyboard.press('Enter');" >> test.js
        echo "    await page.waitForTimeout(5000);" >> test.js
        echo "    await browser.close();" >> test.js
        echo "})();" >> test.js
        node test.js


    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
          name: google-screenshot
          path: screen_shot/
