name: iOS Appium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g appium@2.12.1
          npm install @appium/doctor --location=global
          appium driver install safari
          npm install webdriverio@8.40.6

      - name: Verify Appium installation
        run: appium-doctor --ios

      - name: Start Appium server
        run: |
          appium --log-level debug &> appium.log &
          sleep 10
          cat appium.log

      - name: Start Simulator
        run: xcrun simctl boot "iPhone 15"
        
      - name: Sleep for simulator to boot
        run: sleep 30

      - name: Appium server status
        run: appium --help

      - name: List devices
        run: xcrun simctl list devices

      - name: Run Test Script
        run: |
          cat <<EOF > test.js
          const { remote } = require('webdriverio');

          async function runTest() {
            const driver = await remote({
                'logLevel': 'debug',
                'hostname': '127.0.0.1',
                'port': 4723,
                'capabilities': {
                  'browserName': 'safari',
                  'platformName': 'iOS',
                  'appium:deviceName': 'iPhone 15',
                  'appium:platformVersion': '18.1',
                  'appium:automationName': 'Safari',
                  'safari:useSimulator': true
                }
            });

              await driver.url('https://www.google.com');
              await driver.pause(2000);

              const screenshot = await driver.takeScreenshot();
              require('fs').writeFileSync('screenshot.png', screenshot, 'base64');

              await driver.deleteSession();
          }

          runTest().catch(console.error);
          EOF
          cat test.js
          node test.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
