name: iOS Simulator Test

on:
  workflow_dispatch: # 手動実行のトリガー

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - name: Install dependencies
      run: |
        npm install -g appium
        npm install -g appium-doctor
        npm install wd

    - name: Verify Appium installation
      run: |
        appium-doctor

    - name: Start Appium server
      run: |
        appium & 
        sleep 10  # Wait for Appium server to start

    - name: Start iOS Simulator
      run: |
        xcrun simctl boot "iPhone 15"
        sleep 10  # Wait for the simulator to boot

    - name: xcrun list
      run: xcrun simctl list
    
    - name: Run Test Script
      run: |
        cat <<EOF > test.js
        const wd = require('wd');
        const assert = require('assert');

        const driver = wd.promiseChainRemote('http://localhost:4723/wd/hub');

        async function runTest() {
            await driver.init({
                platformName: 'iOS',
                platformVersion: '18.1',
                deviceName: 'iPhone 15',
                browserName: 'safari', // Safariを起動
            });

            await driver.get('https://www.google.com');
            await driver.sleep(2000); // ページがロードされるのを待つ

            const screenshot = await driver.takeScreenshot();
            require('fs').writeFileSync('screenshot.png', screenshot, 'base64');

            await driver.quit();
        }

        runTest().catch(console.error);
        EOF
        node test.js
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
          name: screenshot
          path: screenshot.png
