name: Playwright Multi Device Test

on:
  workflow_dispatch: # 手動実行のトリガー

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest]
    env:
      RUNNER_OS_MATRIX: ${{ matrix.os }}
      NPM_CACHE_PATH: ${{ matrix.os == 'windows-latest' && 'C:\\Users\\runneradmin\\.npm' || '~/.npm' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ${{ env.NPM_CACHE_PATH }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Show npm Config
        run: npm config list
        
      - name: Install Playwright
        run: |
          npm install @playwright/test
          npx playwright install --with-deps

      - name: Show npm dir
        run: |
          dir 'C:\\npm\\cache'
          dir 'C:\\npm\\prefix'
          dir 'C:\hostedtoolcache\windows\node\22.11.0\'
          dir 'D:\a\playwright_test\playwright_test'
          dir 'C:\Users\runneradmin'
          dir '.\'
          
      - name : Run tests
        run: node runTests.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: google-screenshot-${{ matrix.os }}
          path: screen-shot-${{ matrix.os }}

      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: google-videos-${{ matrix.os }}
          path: videos-${{ matrix.os }}
